[project]
name = "srt_editor"
version = "1.0.0"
description = "Self-hostable SRT editor.."
dependencies = [
    "flask",
    "waitress",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"